/* Generated by makelib.pl, Wed Apr 29 20:09:19 2020 */
#ifndef GR_EDPACKAGE_H_INCLUDED
#define GR_EDPACKAGE_H_INCLUDED
#include <edidentifier.h>
__CIDENT_RCSID(edpackage_h, "$Id: package.h.in,v 1.2 2020/04/29 11:54:24 cvsuser Exp $")
__CPRAGMA_ONCE

/* -*- mode: h; set-indent: 4; -*- */
/* $Id: package.h.in,v 1.2 2020/04/29 11:54:24 cvsuser Exp $
 * Package configuration.
 *
 *
 * Copyright (c) 2015 - 2018, Adam Young.
 * All rights reserved.
 *
 * This file is part of the WinRSH/WinSSH project.
 *
 * The WinRSH/WinSSH project is free software: you can redistribute it
 * and/or modify it under the terms of the WinRSH/WinSSH project License.
 *
 * Redistributions of source code must retain the above copyright
 * notice, and must be distributed with the license document above.
 *
 * Redistributions in binary form must reproduce the above copyright
 * notice, and must include the license document above in
 * the documentation and/or other materials provided with the
 * distribution.
 *
 * The WinRSH/WinSSH project is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * License for more details.
 * ==end==
 *
 * 
 */

/*
 * Build configuration:
 *
 * AC_SUBST(PATHSEP)            @PATHSEP@
 * AC_SUBST(LT_OBJDIR)          .libs/
 * AC_SUBST(SET_MAKE)           MAKEFLAGS=
 *
 * AC_SUBST(RM)                 rm.exe
 * AC_SUBST(TAR)                tar.exe
 * AC_SUBST(PERL)               perl
 * AC_SUBST(INSTALL)            perl D:/devl/winrsh/win32/install.pl
 * AC_SUBST(PROGS)              @PROGS@
 * AC_SUBST(LIBPROGS)           @LIBPROGS@
 *
 * AC_SUBST(CC)                 wcl386
 * AC_SUBST(CXX)                wcl386
 * AC_SUBST(CPPDEP)             @CPPDEP@
 * AC_SUBST(DEFS)               -DHAVE_CONFIG_H -DWIN32=0x501
 * AC_SUBST(CFLAGS)             -q -6r -j -ei -d2  -hw -db -of+ -zlf -bt=nt -bm -br -aa -sg
 * AC_SUBST(CXXFLAGS)           -q -6r -j -ei -d2i     -db -of+ -zlf -bt=nt -bm -br -cc++ -xs -xr
 * AC_SUBST(CWARN)              -W3
 * AC_SUBST(CXXWARN)            -W3
 * AC_SUBST(CINCLUDE)           -i=$(subst /,\,$(ROOT)/libw32) -i=$(subst /,\,$(ROOT)/include)
 * AC_SUBST(LDEBUG)             -q -6r -d2 -hw -db -bt=nt -bm -br
 * AC_SUBST(CDEBUG)             
 * AC_SUBST(CXXDEBUG)           
 * AC_SUBST(LIBCURL_CPPFLAGS)   
 * AC_SUBST(LIBICU_CFLAGS)      @LIBICU_CFLAGS@
 * AC_SUBST(LIBICU_CXXFLAGS)    @LIBICU_CXXFLAGS@
 * AC_SUBST(EXTRA_CFLAGS)       @EXTRA_CFLAGS@
 * AC_SUBST(EXTRA_CXXFLAGS)     @EXTRA_CXXFLAGS@
 *
 * AC_SUBST(LIBTOOL)            perl D:/devl/winrsh/libtool_win32.pl
 * AC_SUBST(LIBTOOL_DEPS)       @LIBTOOL_DEPS@
 * AC_SUBST(LD)                 @LD@
 * AC_SUBST(LDMAPFILE)          -fm=$(MAPFILE)
 *
 * AC_SUBST(LIBS)               $(D_LIB)/libw32.lib
 * AC_SUBST(LIBARCHIVE)         
 * AC_SUBST(LIBEXPLAIN)         @LIBEXPLAIN@
 * AC_SUBST(LIBYACC)            
 * AC_SUBST(LIBCLANG)           @LIBCLANG@
 * AC_SUBST(LIBCURL)            
 * AC_SUBST(LIBENCA)            
 * AC_SUBST(LIBICONV)           
 * AC_SUBST(ICU_CONFIG)         @ICU_CONFIG@
 * AC_SUBST(LIBICU_VERSION)     @LIBICU_VERSION@
 * AC_SUBST(LIBICU)             
 * AC_SUBST(LIBMAGIC)           
 * AC_SUBST(LIBSPELL)           
 * AC_SUBST(TERMLIB)            
 * AC_SUBST(LIBM)               
 * AC_SUBST(LIBX11)             
 * AC_SUBST(EXTRALIBS)          advapi32.lib gdi32.lib shlwapi.lib shell32.lib psapi.lib ole32.lib userenv.lib user32.lib ws2_32.lib wsock32.lib
 * AC_SUBST(LIBMALLOC)          libdlmalloc.lib
 * AC_SUBST(LIBTHREAD)          
 */

#define GR_PACKAGE_BUGREPORT    ""
#define GR_PACKAGE_NAME         ""
#define GR_PACKAGE_STRING       ""
#define GR_PACKAGE_TARNAME      ""
#define GR_PACKAGE_URL          ""
#define GR_PACKAGE_VERSION      ""

#define GR_BUILD                "i386-pc-win32"
#define GR_BUILD_ALIAS          ""
#define GR_BUILD_CPU            "i386"
#define GR_BUILD_OS             "win32"
#define GR_BUILD_VENDOR         "pc"

#define GR_BUILD_CC             "wcl386"
#define GR_BUILD_CFLAGS         "-q -6r -j -ei -d2  -hw -db -of+ -zlf -bt=nt -bm -br -aa -sg"
#define GR_BUILD_CXX            "wcl386"
#define GR_BUILD_CXXFLAGS       "-q -6r -j -ei -d2i     -db -of+ -zlf -bt=nt -bm -br -cc++ -xs -xr"

#define GR_HOST                 "i386-pc-win32"
#define GR_HOST_ALIAS           ""
#define GR_HOST_CPU             "i386"
#define GR_HOST_OS              "win32"
#define GR_HOST_VENDOR          "pc"
#define GR_HOST_SEPARATOR       ";"

#define GR_TARGET               "i386-pc-win32"
#define GR_TARGET_ALIAS         ""
#define GR_TARGET_CPU           "i386"
#define GR_TARGET_OS            "win32"
#define GR_TARGET_VENDOR        "pc"

#endif  /*GR_EDPACKAGE_H_INCLUDED*/

